SELECT EV.WM_CODE
,W.TEAM_CODE
,W.TEAM_SUBCODE
,W.WM_NAME
,W.WM_SURNAME
,W.WM_EMPLOYMENT_DATE
,M.MCH_NUMBER
,M.MT_CODE
,EV.MAT_SAP_CODE
,AV.MD_PPA_VALUE CAL
,EV.EVS_START
,EV.EVS_END
,PP.PP_CYCLE_TIME THEORY_CYCLE_TIME
FROM BR_FS_CAR_FAC_PCS02.HIS_EVENTS EV
INNER JOIN BR_FS_CAR_FAC_PCS02.MD_MACHINES M 
ON EV.MCH_CODE = M.MCH_CODE
INNER JOIN BR_FS_CAR_FAC_PCS02.MD_PROCESS_PARAMETERS PP
ON EV.MAT_SAP_CODE = PP.MAT_SAP_CODE 
INNER JOIN BR_FS_CAR_FAC_PCS02.MD_WORKERS W
ON EV.WM_CODE = W.WM_CODE
INNER JOIN BR_FS_CAR_FAC_PCS02.MD_PROCESS_PARAMETERS_ACYCLE_VALUE AV
ON EV.MAT_SAP_CODE = AV.MAT_SAP_CODE
WHERE EV.PP_CODE = 'CF2' 
AND EV.EV_CODE = 'PROD' 
AND EV.EV_SUBCODE = 'MACH' 
AND EV.EVS_START > TIMESTAMPADD(SQL_TSI_DAY, -{}, NOW())
AND AV.ST_CODE = '011';