SELECT WS.WM_CODE
,M.MCH_NUMBER 
,WS.MAT_SAP_CODE
,WS.WST_QUANTITY  
FROM BR_FS_CAR_FAC_PCS02.WST_WASTE WS
INNER JOIN BR_FS_CAR_FAC_PCS02.MD_MACHINES M
ON WS.MCH_CODE = M.MCH_CODE
INNER JOIN BR_FS_CAR_FAC_PCS02.MD_WORKERS W
ON WS.WM_CODE = W.WM_CODE
WHERE WS.WST_DATE > TIMESTAMPADD(SQL_TSI_DAY, -{}, NOW())
AND WS.PP_CODE = 'CF2'